### PR TITLE
Expanded Notebook Discussion

### PR DESCRIPTION
**Pull request by ssolson**
Thanks, Rebecca!

I added more discussion to the example and I left a couple of questions there for you.

In addition to the ability to somehow check the available data that I brought up on the call this morning (something like available data for NDBC or someway to see it otherwise) I was wondering if we had the ability to return the data within an area such as a polygon or say jurisdiction='California'?

### CODE REVIEW

**Comment by rpauly18** [comment]
@ssolson To answer your 2nd question, yes, you can get data for a particular region. I am thinking that should be a separate function from this one. If so, maybe we should rename this one to "request_WPTO_point_dataset" and we could have a second one called "request_WPTO_region_dataset". Having the two in one function would make us have to differentiate what kind of location input is being given. We would also have to change "lat_lon" to "location" or something similar. What are your thoughts?

**Comment by rpauly18** [comment]
On the idea of a function to get a list of what is available, I am going to need to give it some more thought/ look into it some more. Max at PNNL is also looking into it. I would not want to hold up this PR for it, however.

**Comment by ssolson** [comment]
> @ssolson To answer your 2nd question, yes, you can get data for a particular region. I am thinking that should be a separate function from this one. If so, maybe we should rename this one to "request_WPTO_point_dataset" and we could have a second one called "request_WPTO_region_dataset". Having the two in one function would make us have to differentiate what kind of location input is being given. We would also have to change "lat_lon" to "location" or something similar. What are your thoughts?

I know Ryan is already trying to get a region and is frustrated that it has been so hard to figure out. How hard would it be to add? Maybe we should have a call to refresh on where we are and the future plans for this module?

**Comment by rpauly18** [comment]
I could probably code it up pretty quickly, but I am definitely leaning towards it being a 2nd function in the hindcast submodule. I will try and get a first version of it done tomorrow and added to the PR. Then we can have a call if need be.

**Comment by ssolson** [comment]
I don't want to add unnecessarily to the current load. I am trying to understand where we are. I do think adding "point" to the name would help clarify this idea. I think we should have a strategy meeting and discuss our development priorities maybe we could update the roadmap? Thoughts?

**Pull request closed without merging**
